name: Lavender Springs
favicon: null
layout_spectrum: 0.89161
typography_spectrum: 0.50643
title: Lavender Springs
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3fbfe'
    - '#cab3d0'
    - '#c08bd3'
    - '#9051bc'
    - '#4d2995'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
