name: Lavender Springs
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49805
title: Lavender Springs
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#dae2b3'
    - '#b7c185'
    - '#a69dca'
    - '#675ca0'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
